# Generated by Django 4.0.4 on 2022-05-08 05:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicearea_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='polygon'),
        ),
    ]
